on:
  pull_request:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: build
        if: github.ref == 'refs/heads/main'
        run: |
          echo "build runs"
      - name: normal build
        run: |
          echo "normal runs"
