on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: build
        if: startsWith( github.ref, 'refs/tags/v')
        run: |
          echo "build runs"
