on:
  pull_request:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: build
        if: |
          ${{ startsWith(github.ref, 'refs/tags/v') 
          && (github.event.base_ref  == 'refs/heads/main')}}
        run: |
          echo "build runs"
          echo '${{ github.ref }}'
          echo '${{ github.event.base_ref }}'
      - name: normal build
        run: |
          echo "normal runs"
          echo '${{ toJSON(github) }}'
