on:
  pull_request:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://npm.pkg.github.com"
      - name: build
        if: |
          startsWith(github.ref, 'refs/tags/v') 
            && github.event.base_ref  == 'refs/heads/main'
        run: |
          echo "build runs"
          echo '${{ github.ref }}'
          echo '${{ github.event.base_ref }}'
      - name: normal build
        run: |
          echo "normal runs"
          echo '${{ toJSON(github) }}'
